services:
  detailing-crm-tablet-develop:
    image: ${ENV_DETAILING_CRM_TABLET_IMAGE}
    container_name: ${DETAILING_CRM_TABLET_CONTAINER_NAME}
    ports:
      - '${ENV_DETAILING_CRM_TABLET_EXTERNAL_PORT}:80'
    restart: always
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:8080}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - network

networks:
  network:
    name: ${ENV_NETWORK}
    external: true
